<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace LigthningSale\LnRpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TODO(roasbeef): make str vs bytes into a oneof
 *
 * Generated from protobuf message <code>lnrpc.ChannelPoint</code>
 */
class ChannelPoint extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; Txid of the funding transaction
     *
     * Generated from protobuf field <code>bytes funding_txid = 1[json_name = "funding_txid"];</code>
     */
    private $funding_txid = '';
    /**
     *&#47; Hex-encoded string representing the funding transaction
     *
     * Generated from protobuf field <code>string funding_txid_str = 2[json_name = "funding_txid_str"];</code>
     */
    private $funding_txid_str = '';
    /**
     *&#47; The index of the output of the funding transaction
     *
     * Generated from protobuf field <code>uint32 output_index = 3[json_name = "output_index"];</code>
     */
    private $output_index = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     *&#47; Txid of the funding transaction
     *
     * Generated from protobuf field <code>bytes funding_txid = 1[json_name = "funding_txid"];</code>
     * @return string
     */
    public function getFundingTxid()
    {
        return $this->funding_txid;
    }

    /**
     *&#47; Txid of the funding transaction
     *
     * Generated from protobuf field <code>bytes funding_txid = 1[json_name = "funding_txid"];</code>
     * @param string $var
     * @return $this
     */
    public function setFundingTxid($var)
    {
        GPBUtil::checkString($var, False);
        $this->funding_txid = $var;

        return $this;
    }

    /**
     *&#47; Hex-encoded string representing the funding transaction
     *
     * Generated from protobuf field <code>string funding_txid_str = 2[json_name = "funding_txid_str"];</code>
     * @return string
     */
    public function getFundingTxidStr()
    {
        return $this->funding_txid_str;
    }

    /**
     *&#47; Hex-encoded string representing the funding transaction
     *
     * Generated from protobuf field <code>string funding_txid_str = 2[json_name = "funding_txid_str"];</code>
     * @param string $var
     * @return $this
     */
    public function setFundingTxidStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->funding_txid_str = $var;

        return $this;
    }

    /**
     *&#47; The index of the output of the funding transaction
     *
     * Generated from protobuf field <code>uint32 output_index = 3[json_name = "output_index"];</code>
     * @return int
     */
    public function getOutputIndex()
    {
        return $this->output_index;
    }

    /**
     *&#47; The index of the output of the funding transaction
     *
     * Generated from protobuf field <code>uint32 output_index = 3[json_name = "output_index"];</code>
     * @param int $var
     * @return $this
     */
    public function setOutputIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->output_index = $var;

        return $this;
    }

}

