<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.FeeReportResponse</code>
 */
class FeeReportResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; An array of channel fee reports which describes the current fee schedule for each channel.
     *
     * Generated from protobuf field <code>repeated .lnrpc.ChannelFeeReport channel_fees = 1[json_name = "channel_fees"];</code>
     */
    private $channel_fees;

    public function __construct()
    {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     *&#47; An array of channel fee reports which describes the current fee schedule for each channel.
     *
     * Generated from protobuf field <code>repeated .lnrpc.ChannelFeeReport channel_fees = 1[json_name = "channel_fees"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChannelFees()
    {
        return $this->channel_fees;
    }

    /**
     *&#47; An array of channel fee reports which describes the current fee schedule for each channel.
     *
     * Generated from protobuf field <code>repeated .lnrpc.ChannelFeeReport channel_fees = 1[json_name = "channel_fees"];</code>
     * @param \Lnrpc\ChannelFeeReport[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChannelFees($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\ChannelFeeReport::class);
        $this->channel_fees = $arr;

        return $this;
    }
}
