<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace LightningSale\Lnrpc;

/**
 * Protobuf enum <code>LightningSale\Lnrpc\NewAddressRequest\AddressType</code>
 */
class NewAddressRequest_AddressType
{
    /**
     * Generated from protobuf enum <code>WITNESS_PUBKEY_HASH = 0;</code>
     */
    const WITNESS_PUBKEY_HASH = 0;
    /**
     * Generated from protobuf enum <code>NESTED_PUBKEY_HASH = 1;</code>
     */
    const NESTED_PUBKEY_HASH = 1;
    /**
     * Generated from protobuf enum <code>PUBKEY_HASH = 2;</code>
     */
    const PUBKEY_HASH = 2;
}

